# Generated by Django 6.0.7 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="entry_mode",
            field=models.CharField(
                choices=[
                    ("WALK_IN", "Walk In"),
                    ("HOME_COLLECTION", "Home Collection"),
                    ("ONLINE", "Online"),
                    ("DOCTOR_REFERRAL", "Doctor Referral"),
                ],
                default="WALK_IN",
                max_length=20,
            ),
        ),
    ]
