# Generated by Django 6.0.7 on 2026-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_branch_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PATHOLOGIST', 'Pathologist'), ('PATIENT', 'Patient')], default='RECEPTIONIST', max_length=20),
        ),
    ]
