# Generated by Django 6.0.7 on 2026-07-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_appointment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='visits_appo_patient_46f1d3_idx',
            old_name='visits_app_patient_1d10af_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='visits_appo_schedul_78e2dd_idx',
            old_name='visits_app_schedul_39f949_idx',
        ),
    ]
