# Generated by Django 6.0.7 on 2026-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_rename_visits_app_patient_1d10af_idx_visits_appo_patient_46f1d3_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Awaiting Acceptance)'), ('ACCEPTED', 'Accepted by Technician'), ('VISITED', 'Patient Visited / Technician Visited Home'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('TESTED', 'Testing Completed'), ('UNDER_REVIEW', 'Under Review (Pathologist/Owner)'), ('APPROVED', 'Approved — Report Ready'), ('REJECTED', 'Rejected — Values Need Correction'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('BOOKED', 'Booked')], default='PENDING', max_length=25),
        ),
    ]
