# Generated by Django 6.0.7 on 2026-07-25 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_orderedtest'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=20, unique=True)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('SWAB', 'Swab')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='visits.visit')),
            ],
        ),
        migrations.AddField(
            model_name='orderedtest',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_tests', to='laboratory.sample'),
        ),
    ]
