# Generated by Django 6.0.7 on 2026-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_result_resultparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultparameter',
            name='flag',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='resultparameter',
            name='reference_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
