# Generated by Django 6.0.7 on 2026-07-28 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='inventory_reorder_level_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_usage_quantity_positive'),
        ),
    ]
