# Generated by Django 6.0.7 on 2026-07-25 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('IMMUNOLOGY', 'Immunology'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology')], max_length=30)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('SWAB', 'Swab')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
