# Generated by Django 6.0.7 on 2026-07-25 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_tests', to='laboratory.laboratorytest')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_tests', to='visits.visit')),
            ],
        ),
    ]
