# Generated by Django 6.0.7 on 2026-07-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_resultparameter_flag_resultparameter_reference_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testparameter',
            name='reference_range',
        ),
    ]
