# Generated by Django 6.0.7 on 2026-07-26 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_remove_testparameter_reference_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='price',
        ),
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walk_in_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='laboratory.package')),
            ],
        ),
        migrations.CreateModel(
            name='TestPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walk_in_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='laboratory.laboratorytest')),
            ],
        ),
        migrations.CreateModel(
            name='PackageTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('laboratory_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_tests', to='laboratory.laboratorytest')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_tests', to='laboratory.package')),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('package', 'laboratory_test'), name='unique_test_per_package')],
            },
        ),
    ]
