# Generated by Django 6.0.7 on 2026-07-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_package_remove_laboratorytest_price_packageprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameter',
            name='reference_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
