# Generated by Django 6.0.7 on 2026-07-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
